Added fullfacet call on selected filter
SciCatProject/frontend-react pull request #2
Opened 2024-03-14 10:33 UTC by signelindstrom

When filter is selected, the fullfacet endpoint is called again to only show relevant options for current selected filter

2024-03-19 07:30 UTC, Junjiequan requested changes
Left a small comment. 
Other than that my suggestion is to start with state management as soon as possible. Currently you are managing data fetch in every component. It's fine for now, as only fullquery and fullfacet request is used. But later it will become much harder to manage, especially when you need to make request to more than 2 endpoints or even more within the same service.

2024-03-19 07:30 UTC, Junjiequan commented on src/components/search/filters/FetchFullfacet.tsx
> +        let updatedUrl = 'http://localhost:3000/api/v3/datasets/fullfacet?facets=["type","creationLocation","ownerGroup","keywords"]&fields={}';
I see the url is hard coded several places. The `http://localhost:3000/api/v3`  should be in one place and can be configured, as we know for sure we need to change it later.

2024-03-20 14:00 UTC, Junjiequan approved these changes
Left one comment, otherwise looks fine to me

2024-03-20 14:05 UTC, signelindstrom commented on config.tsx
> +export const BASE_URL = 'http://localhost:3000/api/v3/'
Yes, you are right!

2024-03-21 10:29 UTC, merged